### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by PoIygon**
These make the issues page actually useable and easier to use

### CODE REVIEW

**Comment by CluckCluckChicken** [comment]
im not sure something as small as potatophant.net needs issue templates?

**Comment by PoIygon** [comment]
> 
> 
> im not sure something as small as potatophant.net needs issue templates?

**ISSUE TEMPLATES**

**Comment by CluckCluckChicken** [comment]
fine :P

**Comment by FunctionalMetatable** [comment]
poiygon has local development environment?????

**Comment by CluckCluckChicken** [comment]
o-o

**Pull request merged**
